/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;
import routes.Routes;
import service.UsuarioService;
import session.DadosSession;

import java.awt.Image;
import java.awt.Graphics;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class Catalago1 extends javax.swing.JFrame {

    private Routes rotas = new Routes();
    private UsuarioService usuarioService = new UsuarioService();

    /**
     * Creates new form Catalago1
     */
    public Catalago1() {
        if(DadosSession.existeUsuarioLogado()){
            initComponents();
            calcularValorAluguel();
        } else {
            rotas.goLogin();
        }

    }

    private void calcularValorAluguel() {
        System.out.println(DadosSession.getDataRetirada());
        //Date dataRetirada = new Date(DadosSession.getDataRetirada());
        //Date dataDevolucao = new Date(DadosSession.getDataDevolucao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/fundo.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        GrupoA = new javax.swing.JLabel();
        CardGol = new javax.swing.JPanel();
        NomeGol = new javax.swing.JLabel();
        FotoGol = new javax.swing.JLabel();
        AlugarGol = new javax.swing.JButton();
        RetiradaGol = new javax.swing.JLabel();
        DevolucaoGol = new javax.swing.JLabel();
        DataRetiradaGol = new javax.swing.JLabel();
        HoraRetiradaGol = new javax.swing.JLabel();
        DataDevolucaoGol = new javax.swing.JLabel();
        HoraDevolucaoGol = new javax.swing.JLabel();
        LocalGol = new javax.swing.JLabel();
        ValorGol = new javax.swing.JLabel();
        CardKwid = new javax.swing.JPanel();
        NomeKwid = new javax.swing.JLabel();
        FotoKwid = new javax.swing.JLabel();
        AlugarKwid = new javax.swing.JButton();
        RetiradaKwid = new javax.swing.JLabel();
        DevolucaoKwid = new javax.swing.JLabel();
        DataRetiradaKwid = new javax.swing.JLabel();
        DataDevolucaoKwid = new javax.swing.JLabel();
        HoraRetiradaKwid = new javax.swing.JLabel();
        HoraDevolucaooKwid = new javax.swing.JLabel();
        LocalKwid = new javax.swing.JLabel();
        ValorKwid = new javax.swing.JLabel();
        CardUno = new javax.swing.JPanel();
        NomeUno = new javax.swing.JLabel();
        FotoUno = new javax.swing.JLabel();
        AlugarUno = new javax.swing.JButton();
        RetiradaUno = new javax.swing.JLabel();
        DevolucaoUno = new javax.swing.JLabel();
        DataRetiradaUno = new javax.swing.JLabel();
        DataDevolucaoUno = new javax.swing.JLabel();
        HoraRetiradaUno = new javax.swing.JLabel();
        HoraDevolucaoUno = new javax.swing.JLabel();
        LocalUno = new javax.swing.JLabel();
        ValorUno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        Proximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GoCar Locadora de Carros");
        setBackground(new java.awt.Color(0, 0, 0));

        GrupoA.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        GrupoA.setForeground(new java.awt.Color(255, 255, 0));
        GrupoA.setText("Grupo A - Econômicos");

        CardGol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NomeGol.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        NomeGol.setText("VW GOL 1.0");

        FotoGol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Gol.png"))); // NOI18N

        AlugarGol.setBackground(new java.awt.Color(255, 255, 51));
        AlugarGol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlugarGol.setText("Alugar");

        RetiradaGol.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        RetiradaGol.setText("Retirada");

        DevolucaoGol.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        DevolucaoGol.setText("Devolução");

        DataRetiradaGol.setText("Data");

        HoraRetiradaGol.setText("Hora");

        DataDevolucaoGol.setText("Data");

        HoraDevolucaoGol.setText("Hora");

        LocalGol.setText("Local");

        ValorGol.setText("Valor");

        javax.swing.GroupLayout CardGolLayout = new javax.swing.GroupLayout(CardGol);
        CardGol.setLayout(CardGolLayout);
        CardGolLayout.setHorizontalGroup(
            CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardGolLayout.createSequentialGroup()
                .addComponent(FotoGol, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardGolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomeGol)
                .addGap(102, 102, 102))
            .addGroup(CardGolLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(RetiradaGol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DevolucaoGol)
                .addGap(36, 36, 36))
            .addGroup(CardGolLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(AlugarGol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CardGolLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LocalGol)
                    .addComponent(HoraRetiradaGol)
                    .addComponent(DataRetiradaGol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardGolLayout.createSequentialGroup()
                        .addComponent(ValorGol)
                        .addGap(68, 68, 68))
                    .addGroup(CardGolLayout.createSequentialGroup()
                        .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraDevolucaoGol)
                            .addComponent(DataDevolucaoGol))
                        .addContainerGap())))
        );
        CardGolLayout.setVerticalGroup(
            CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardGolLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(NomeGol)
                .addGap(18, 18, 18)
                .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FotoGol, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CardGolLayout.createSequentialGroup()
                        .addGap(0, 183, Short.MAX_VALUE)
                        .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RetiradaGol)
                            .addComponent(DevolucaoGol))))
                .addGap(13, 13, 13)
                .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataRetiradaGol)
                    .addComponent(DataDevolucaoGol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraRetiradaGol)
                    .addComponent(HoraDevolucaoGol))
                .addGap(43, 43, 43)
                .addGroup(CardGolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalGol)
                    .addComponent(ValorGol))
                .addGap(32, 32, 32)
                .addComponent(AlugarGol)
                .addGap(21, 21, 21))
        );

        NomeKwid.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        NomeKwid.setText("Kwid 1.0");

        FotoKwid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kwid.png"))); // NOI18N

        AlugarKwid.setBackground(new java.awt.Color(255, 255, 0));
        AlugarKwid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlugarKwid.setText("Alugar");

        RetiradaKwid.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        RetiradaKwid.setText("Retirada");

        DevolucaoKwid.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        DevolucaoKwid.setText("Devolução");

        DataRetiradaKwid.setText("Data");

        DataDevolucaoKwid.setText("Data");

        HoraRetiradaKwid.setText("Hora");

        HoraDevolucaooKwid.setText("Hora");

        LocalKwid.setText("Local");

        ValorKwid.setText("Valor");

        javax.swing.GroupLayout CardKwidLayout = new javax.swing.GroupLayout(CardKwid);
        CardKwid.setLayout(CardKwidLayout);
        CardKwidLayout.setHorizontalGroup(
            CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardKwidLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardKwidLayout.createSequentialGroup()
                        .addComponent(NomeKwid)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardKwidLayout.createSequentialGroup()
                        .addComponent(AlugarKwid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardKwidLayout.createSequentialGroup()
                        .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(CardKwidLayout.createSequentialGroup()
                                .addComponent(RetiradaKwid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DevolucaoKwid))
                            .addComponent(FotoKwid))
                        .addGap(27, 27, 27))))
            .addGroup(CardKwidLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardKwidLayout.createSequentialGroup()
                        .addComponent(LocalKwid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorKwid))
                    .addGroup(CardKwidLayout.createSequentialGroup()
                        .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataRetiradaKwid)
                            .addComponent(HoraRetiradaKwid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataDevolucaoKwid)
                            .addComponent(HoraDevolucaooKwid))))
                .addGap(49, 49, 49))
        );
        CardKwidLayout.setVerticalGroup(
            CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardKwidLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(NomeKwid)
                .addGap(28, 28, 28)
                .addComponent(FotoKwid)
                .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardKwidLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RetiradaKwid)
                            .addComponent(DevolucaoKwid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                    .addGroup(CardKwidLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DataRetiradaKwid)
                            .addComponent(DataDevolucaoKwid))))
                .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraRetiradaKwid)
                    .addComponent(HoraDevolucaooKwid))
                .addGap(31, 31, 31)
                .addGroup(CardKwidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalKwid)
                    .addComponent(ValorKwid))
                .addGap(33, 33, 33)
                .addComponent(AlugarKwid)
                .addGap(24, 24, 24))
        );

        NomeUno.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        NomeUno.setText("Uno 1.0");

        FotoUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/uno.png"))); // NOI18N

        AlugarUno.setBackground(new java.awt.Color(255, 255, 0));
        AlugarUno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AlugarUno.setText("Alugar");

        RetiradaUno.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        RetiradaUno.setText("Retirada");

        DevolucaoUno.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        DevolucaoUno.setText("Devolução");

        DataRetiradaUno.setText("Data");

        DataDevolucaoUno.setText("Data");

        HoraRetiradaUno.setText("Hora");

        HoraDevolucaoUno.setText("Hora");

        LocalUno.setText("Local");

        ValorUno.setText("Valor");

        javax.swing.GroupLayout CardUnoLayout = new javax.swing.GroupLayout(CardUno);
        CardUno.setLayout(CardUnoLayout);
        CardUnoLayout.setHorizontalGroup(
            CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardUnoLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardUnoLayout.createSequentialGroup()
                        .addComponent(NomeUno)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardUnoLayout.createSequentialGroup()
                        .addComponent(AlugarUno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardUnoLayout.createSequentialGroup()
                        .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(CardUnoLayout.createSequentialGroup()
                                .addComponent(RetiradaUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DevolucaoUno))
                            .addComponent(FotoUno, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(25, 25, 25))))
            .addGroup(CardUnoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CardUnoLayout.createSequentialGroup()
                        .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CardUnoLayout.createSequentialGroup()
                                .addComponent(HoraRetiradaUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HoraDevolucaoUno))
                            .addGroup(CardUnoLayout.createSequentialGroup()
                                .addComponent(DataRetiradaUno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DataDevolucaoUno)))
                        .addGap(53, 53, 53))
                    .addGroup(CardUnoLayout.createSequentialGroup()
                        .addComponent(LocalUno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ValorUno)
                        .addGap(52, 52, 52))))
        );
        CardUnoLayout.setVerticalGroup(
            CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardUnoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(NomeUno)
                .addGap(31, 31, 31)
                .addComponent(FotoUno)
                .addGap(44, 44, 44)
                .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RetiradaUno)
                    .addComponent(DevolucaoUno))
                .addGap(18, 18, 18)
                .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataRetiradaUno)
                    .addComponent(DataDevolucaoUno))
                .addGap(18, 18, 18)
                .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoraRetiradaUno)
                    .addComponent(HoraDevolucaoUno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(CardUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalUno)
                    .addComponent(ValorUno))
                .addGap(24, 24, 24)
                .addComponent(AlugarUno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logop.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        Voltar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar(evt);
            }
        });

        Proximo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Proximo.setText("Proximo");
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximo(evt);
            }
        });

        jDesktopPane1.setLayer(GrupoA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CardGol, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CardKwid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CardUno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Proximo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(299, 299, 299)
                        .addComponent(GrupoA)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 89, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(CardGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(CardKwid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(CardUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(Voltar)
                                .addGap(214, 214, 214)
                                .addComponent(Proximo)
                                .addGap(496, 496, 496))))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(GrupoA)
                .addGap(32, 32, 32)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardKwid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proximo)
                    .addComponent(Voltar))
                .addGap(37, 37, 37))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(CardGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.rotas.goAlugar();
        fecharCatalogo1();
    }

    private void proximo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.rotas.goCatalogo2();
        fecharCatalogo1();
    }

    private void fecharCatalogo1() {
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalago1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalago1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalago1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalago1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalago1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlugarGol;
    private javax.swing.JButton AlugarKwid;
    private javax.swing.JButton AlugarUno;
    private javax.swing.JPanel CardGol;
    private javax.swing.JPanel CardKwid;
    private javax.swing.JPanel CardUno;
    private javax.swing.JLabel DataDevolucaoGol;
    private javax.swing.JLabel DataDevolucaoKwid;
    private javax.swing.JLabel DataDevolucaoUno;
    private javax.swing.JLabel DataRetiradaGol;
    private javax.swing.JLabel DataRetiradaKwid;
    private javax.swing.JLabel DataRetiradaUno;
    private javax.swing.JLabel DevolucaoGol;
    private javax.swing.JLabel DevolucaoKwid;
    private javax.swing.JLabel DevolucaoUno;
    private javax.swing.JLabel FotoGol;
    private javax.swing.JLabel FotoKwid;
    private javax.swing.JLabel FotoUno;
    private javax.swing.JLabel GrupoA;
    private javax.swing.JLabel HoraDevolucaoGol;
    private javax.swing.JLabel HoraDevolucaoUno;
    private javax.swing.JLabel HoraDevolucaooKwid;
    private javax.swing.JLabel HoraRetiradaGol;
    private javax.swing.JLabel HoraRetiradaKwid;
    private javax.swing.JLabel HoraRetiradaUno;
    private javax.swing.JLabel LocalGol;
    private javax.swing.JLabel LocalKwid;
    private javax.swing.JLabel LocalUno;
    private javax.swing.JLabel NomeGol;
    private javax.swing.JLabel NomeKwid;
    private javax.swing.JLabel NomeUno;
    private javax.swing.JButton Proximo;
    private javax.swing.JLabel RetiradaGol;
    private javax.swing.JLabel RetiradaKwid;
    private javax.swing.JLabel RetiradaUno;
    private javax.swing.JLabel ValorGol;
    private javax.swing.JLabel ValorKwid;
    private javax.swing.JLabel ValorUno;
    private javax.swing.JButton Voltar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
